version: '3.8'

services:
  quest-timer:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    container_name: quest-timer-app
    ports:
      - "3046:80"
    restart: unless-stopped
    # 🔥 VOLUME SOURCE COMPLET: /home/jynra/Projects/quest-timer → nginx
    volumes:
      # Monte TOUT le projet source (sans :ro pour éviter les problèmes)
      - ../:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s