version: '3.8'

services:
  quest-timer:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    container_name: quest-timer-app
    ports:
      - "3046:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quest-timer.rule=Host(`localhost`)"
      - "traefik.http.services.quest-timer.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s